#!/usr/bin/env python3
import pika
import json
from datetime import datetime
import elasticsearch
import ssl


es = elasticsearch.Elasticsearch()


def callback(ch, method, properties, body):
    received_at = datetime.utcnow()

    body = json.loads(body.decode())

    if body.get('node_id', None):
        ts = datetime.strptime(body['@timestamp'], '%Y/%m/%d %H:%M:%S')

        body['lag'] = (received_at - ts).total_seconds()

        es.index(index=ts.strftime('metric-%Y.%m.%d'),
                 doc_type='system',
                 body=body)

    print(body, flush=True)

    channel.basic_ack(delivery_tag=method.delivery_tag)


parameters = pika.ConnectionParameters(
    host='beehive1.mcs.anl.gov',
    port=23181,
    credentials=pika.PlainCredentials('node', 'waggle'),
    ssl=True,
    ssl_options={
        'certfile': '/Users/Sean/waggle-sensor/metrics/ssl/cert.pem',
        'keyfile': '/Users/Sean/waggle-sensor/metrics/ssl/key.pem',
        'ca_certs': '/Users/Sean/waggle-sensor/metrics/ssl/ca.pem',
        'cert_reqs': ssl.CERT_REQUIRED,
    })

connection = pika.BlockingConnection(parameters)
channel = connection.channel()

channel.basic_consume(callback, queue='metrics')
channel.start_consuming()
